// GENERATED by scripts/render.mjs from pool-edge.config.json. Do not edit.
// The test suite re-renders and compares; hand edits are a test failure.
export const EDGE_CONFIG = Object.freeze({
  "edgeName": "example-pool-edge",
  "publicOrigin": "https://pool.army.example.com",
  "allowedOrigins": [
    "https://pool.army.example.com",
    "https://army.example.com"
  ],
  "tokenPrefix": "army_",
  "tiers": {
    "contributor": {
      "name": "contributor",
      "weightedTokens": 25000000,
      "models": null
    },
    "proven": {
      "name": "proven",
      "weightedTokens": 150000000,
      "models": null
    },
    "probation": {
      "name": "probation",
      "weightedTokens": 2000000,
      "models": [
        "claude-fable-5",
        "claude-sonnet-4-6"
      ]
    }
  },
  "grantIncreaseNote": "Merged work earns an increase: ask the pool operator.",
  "passthroughAssets": []
});
