#!/usr/bin/env node
/**
 * render.mjs — the template's build step.
 *
 * Reads pool-edge.config.json (or the file named in argv[1]), validates it
 * fail-closed, and renders the two derived files:
 *
 *   src/edge.gen.js   the worker's identity module. The worker imports ONLY
 *                     this for instance-specific values; no identity string
 *                     lives in worker source.
 *   wrangler.toml     deploy manifest: worker name, custom-domain route,
 *                     UPSTREAM_BASE_URL / PUBLIC_BASE_URL vars, KV binding.
 *
 * Deterministic: the same config renders byte-identical output. Both rendered
 * files are committed, and the test suite re-renders and compares so drift
 * between config and render is a test failure, not a silent skew.
 *
 * Secrets are NEVER rendered. POOL_EDGE_KEY is a wrangler secret; see README.
 */

import { writeFileSync } from 'node:fs';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

import { loadConfig } from './lib/config.mjs';

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), '..');

export function renderEdgeGen(config) {
  const payload = {
    edgeName: config.edgeName,
    publicOrigin: config.publicOrigin,
    allowedOrigins: [...config.allowedOrigins],
    tokenPrefix: config.tokenPrefix,
    tiers: Object.fromEntries(
      Object.entries(config.tiers).map(([name, tier]) => [
        name,
        { name, weightedTokens: tier.weightedTokens, models: tier.models ? [...tier.models] : null },
      ]),
    ),
    grantIncreaseNote: config.grantIncreaseNote,
    passthroughAssets: [...config.passthroughAssets],
  };
  return (
    '// GENERATED by scripts/render.mjs from pool-edge.config.json. Do not edit.\n' +
    '// The test suite re-renders and compares; hand edits are a test failure.\n' +
    `export const EDGE_CONFIG = Object.freeze(${JSON.stringify(payload, null, 2)});\n`
  );
}

export function renderWranglerToml(config) {
  const host = new URL(config.publicOrigin).host;
  const kvLine = config.kvNamespaceId
    ? `id = "${config.kvNamespaceId}"`
    : '# id = "<paste the id from: wrangler kv namespace create POOL_EDGE>"';
  return `# GENERATED by scripts/render.mjs from pool-edge.config.json. Do not edit.
#
# The hostname IS the product name. Custom domain binding, not a DNS CNAME to
# the pool origin: DNS pointing at the pool would publish its whole admin
# surface on this hostname. The Worker allowlists the public pages and seals
# /admin, /ledger, /meter and /byo.

name = "${config.edgeName}"
main = "src/worker.js"
compatibility_date = "2026-07-30"
workers_dev = false

routes = [
  { pattern = "${host}", custom_domain = true }
]

[vars]
UPSTREAM_BASE_URL = "${config.poolBaseUrl}"
PUBLIC_BASE_URL = "${config.publicOrigin}"
# Flip to "on" and redeploy (or \`wrangler secret put KILL_SWITCH\`) to pause
# all inference without touching DNS, the pool, or anyone's grant.
KILL_SWITCH = "off"

# Contributor grants. Create with: wrangler kv namespace create POOL_EDGE
[[kv_namespaces]]
binding = "POOL_EDGE"
${kvLine}

# Secrets, set via \`wrangler secret put <NAME>\` and never committed:
#   POOL_EDGE_KEY  the dedicated pool key minted for this edge on the upstream
#                  pool (own quota, traces off). See README "Secrets".

[observability]
enabled = true

[observability.logs]
# Token counts and status only. The Worker never logs prompt or response bodies.
enabled = true
`;
}

const isMain = process.argv[1] && resolve(process.argv[1]) === fileURLToPath(import.meta.url);
if (isMain) {
  const configPath = resolve(process.argv[2] || join(ROOT, 'pool-edge.config.json'));
  const config = loadConfig(configPath);
  writeFileSync(join(ROOT, 'src/edge.gen.js'), renderEdgeGen(config));
  writeFileSync(join(ROOT, 'wrangler.toml'), renderWranglerToml(config));
  if (!config.kvNamespaceId) {
    process.stderr.write(
      '[pool-edge] warning: kv.namespaceId is empty. Create the namespace and paste the id before deploying:\n' +
        '  wrangler kv namespace create POOL_EDGE\n',
    );
  }
  process.stdout.write(`[pool-edge] rendered src/edge.gen.js + wrangler.toml for ${config.edgeName}\n`);
}
